export const RMV_FROM_SHOPPING_CART = "RMV_FROM_SHOPPING_CART";
export const RMV_TYPE_FROM_SHOPPING_CART = "RMV_TYPE_FROM_SHOPPING_CART";
export const ADD_TO_SHOPPING_CART = "ADD_TO_SHOPPING_CART";
export const CLEAR_SHOPPING_CART = "CLEAR_SHOPPING_CART";



export const RMV_TYPE_FROM_FAVORITE_CART = "RMV_TYPE_FROM_FAVORITE_CART";
export const RMV_FROM_FAVORITE_CART = "RMV_FROM_FAVORITE_CART";
export const ADD_TO_FAVORITE_CART = "ADD_TO_FAVORITE_CART";
export const CLEAR_FAVORITE_CART = "CLEAR_FAVORITE_CART";

export const CURRENT_BEER = "CURRENT_BEER";

export const FETCH_BEGIN_ = "FETCH_BEGIN_";
export const FETCH_SUCCESS_ = "FETCH_SUCCESS_";
export const FETCH_FAIL_ = "FETCH_FAIL_";

export const FETCH_BEGIN_OFFER = "FETCH_BEGIN_OFFER";
export const FETCH_SUCCESS_OFFER = "FETCH_SUCCESS_OFFER";
export const FETCH_FAIL_OFFER = "FETCH_FAIL_OFFER";

export const FETCH_BEGIN_JWT = "FETCH_BEGIN_JWT";
export const FETCH_SUCCESS_JWT = "FETCH_SUCCESS_JWT";
export const FETCH_FAIL_JWT = "FETCH_FAIL_JWT";

export const FETCH_BEGIN_FILTERS = "FETCH_BEGIN_FILTERS";
export const FETCH_SUCCESS_FILTERS = "FETCH_SUCCESS_FILTERS";
export const FETCH_FAIL_FILTERS = "FETCH_FAIL_FILTERS";

export const INCR_ORDER = "INCR_ORDER";
export const DECR_ORDER = "DECR_ORDER";

export const VALID = "VALID";
export const NOT_VALID = "NOT_VALID";


